version: '3.3'

services:
  domoticz:
    image: domoticz/domoticz:stable
    container_name: domoticz
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config:/opt/domoticz/userdata
      - /sys/bus/w1/devices:/sys/bus/w1/devices:ro
    environment:
      - TZ=America/Toronto
